name: hodi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.1.1
  permission_handler: ^11.3.1
  transparent_image: ^2.0.1
  provider: ^5.0.0
  path_provider: ^2.1.2
  http: ^1.2.1
  internet_connection_checker_plus: ^2.3.0
  external_path: ^1.0.3
  media_scanner: ^2.1.0
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
